// Generated by gencpp from file optitrack/RigidBodyArray.msg
// DO NOT EDIT!


#ifndef OPTITRACK_MESSAGE_RIGIDBODYARRAY_H
#define OPTITRACK_MESSAGE_RIGIDBODYARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <optitrack/RigidBody.h>

namespace optitrack
{
template <class ContainerAllocator>
struct RigidBodyArray_
{
  typedef RigidBodyArray_<ContainerAllocator> Type;

  RigidBodyArray_()
    : header()
    , bodies()  {
    }
  RigidBodyArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bodies(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::optitrack::RigidBody_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::optitrack::RigidBody_<ContainerAllocator> >::other >  _bodies_type;
  _bodies_type bodies;




  typedef boost::shared_ptr< ::optitrack::RigidBodyArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optitrack::RigidBodyArray_<ContainerAllocator> const> ConstPtr;

}; // struct RigidBodyArray_

typedef ::optitrack::RigidBodyArray_<std::allocator<void> > RigidBodyArray;

typedef boost::shared_ptr< ::optitrack::RigidBodyArray > RigidBodyArrayPtr;
typedef boost::shared_ptr< ::optitrack::RigidBodyArray const> RigidBodyArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optitrack::RigidBodyArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optitrack::RigidBodyArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optitrack

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'optitrack': ['/home/peter/crazyflie_ws/src/optitrack/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::RigidBodyArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optitrack::RigidBodyArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::RigidBodyArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optitrack::RigidBodyArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::RigidBodyArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optitrack::RigidBodyArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optitrack::RigidBodyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f986085eb31708c02ac750a1c1b0e27d";
  }

  static const char* value(const ::optitrack::RigidBodyArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf986085eb31708c0ULL;
  static const uint64_t static_value2 = 0x2ac750a1c1b0e27dULL;
};

template<class ContainerAllocator>
struct DataType< ::optitrack::RigidBodyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optitrack/RigidBodyArray";
  }

  static const char* value(const ::optitrack::RigidBodyArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optitrack::RigidBodyArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Optitrack rigid bodies\n\
Header                  header\n\
optitrack/RigidBody[]  bodies\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: optitrack/RigidBody\n\
# Optitrack rigid body\n\
int32                 id\n\
bool                  tracking_valid\n\
float64               mrk_mean_error\n\
geometry_msgs/Pose    pose\n\
geometry_msgs/Point[] markers\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::optitrack::RigidBodyArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optitrack::RigidBodyArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bodies);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RigidBodyArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optitrack::RigidBodyArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optitrack::RigidBodyArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bodies[]" << std::endl;
    for (size_t i = 0; i < v.bodies.size(); ++i)
    {
      s << indent << "  bodies[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::optitrack::RigidBody_<ContainerAllocator> >::stream(s, indent + "    ", v.bodies[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTITRACK_MESSAGE_RIGIDBODYARRAY_H
