language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
before_install:
  # Define some config vars
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - echo "Testing branch $TRAVIS_BRANCH "
  - pwd
  # Dependencies
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y python-catkin-pkg python-pip python-rosdep python-wstool ros-$ROS_DISTRO-roscpp
  - pip install optirx --user
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install:
  # Create workspace
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - wstool init .
  # Clone required repositories
  - git clone https://github.com/crigroup/optitrack.git -b hydro-devel
  - git clone https://github.com/gt-ros-pkg/hrl-kdl.git -b hydro
  - cd ~/catkin_ws
  # Install ros dependencies
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash  
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  # TEST 1 -------------------------------------------
  - echo "Test 1 ========================================"
  - catkin_make DCMAKE_BUILD_TYPE=Debug
